[build.environment]
  # Overrides the version pinned in the Netlify UI / build image default
  NODE_VERSION = "24"

[[headers]]
  for = "/*"
  [headers.values]

  # CORS
  # Cross-Origin-Embedder-Policy = "require-corp"
  # Cross-Origin-Opener-Policy = "same-origin"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
